/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GenomeBrowser;

import GenomeBrowser.utilities.TextPaneUtil;
import au.com.bytecode.opencsv.CSVReader;
import java.awt.Component;
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author davidoluwasusi
 */
public class GenomeFrame extends javax.swing.JFrame {

    private String fastaPath;

    public JFrame getOwnFrame() {
        return this;
    }

    /**
     * Creates new form GenomeFrame
     */
    public GenomeFrame() {
        initComponents();
    }

    private String processSelectedFile(FileDialog nameBox) {
        try {
            String fileDirectory = nameBox.getDirectory();
            String fileName = nameBox.getFile();
            fileName = fileDirectory.concat(fileName);
            return fileName;
        } catch (Exception error) {
            //an error occured return an empty path to trigger validation
            error.printStackTrace();
            return "";
        }
    }

    private Object[][] parseGffFile(String filePath) {
        List<Object[]> dataList = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("#")) {
                    continue; // Skip comments and metadata
                }
                String[] fields = line.split("\t");
                if (fields.length < 9) {
                    continue; // Ensure correct format
                }
                // Parse attributes (GFF2 style: ID "..." format)
                String attributes = fields[8].replace("\"", ""); // Remove double quotes

                Object[] row = {
                    fields[0], // Chromosome
                    fields[1], // Source
                    fields[2], // Feature Type
                    Integer.parseInt(fields[3]), // Start Position
                    Integer.parseInt(fields[4]), // End Position
                    fields[5], // Score
                    fields[6], // Strand
                    fields[7], // Phase
                    attributes // Attributes
                };
                dataList.add(row);
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error reading GFF file!", "File Error", JOptionPane.ERROR_MESSAGE);
        }
        return dataList.toArray(new Object[0][]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        geneDetailtabViewSection = new javax.swing.JTabbedPane();
        overviewTab = new javax.swing.JPanel();
        sequenceViewerOverview = new GenomeBrowser.SequenceViewer();
        tableViewerOverviewGtfTable = new GenomeBrowser.TableViewer();
        basicStatsTab = new javax.swing.JPanel();
        basicStatisticsPanelOverview = new GenomeBrowser.BasicStatisticsPanel();
        exploreGenesTab = new javax.swing.JPanel();
        geneExplorerOverview = new GenomeBrowser.GeneExplorer();
        fileUploadPanel5 = new GenomeBrowser.FileUploadPanel();
        fileUploadArea = new javax.swing.JPanel();
        gtfFileUploadButton = new javax.swing.JButton();
        fastaFileUploadButton = new javax.swing.JButton();
        fileSelectedLabel = new javax.swing.JLabel();
        fastaFileSelectedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));

        geneDetailtabViewSection.setToolTipText("");

        javax.swing.GroupLayout overviewTabLayout = new javax.swing.GroupLayout(overviewTab);
        overviewTab.setLayout(overviewTabLayout);
        overviewTabLayout.setHorizontalGroup(
            overviewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sequenceViewerOverview, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
            .addGroup(overviewTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableViewerOverviewGtfTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overviewTabLayout.setVerticalGroup(
            overviewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewTabLayout.createSequentialGroup()
                .addComponent(tableViewerOverviewGtfTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sequenceViewerOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        geneDetailtabViewSection.addTab("Overview", overviewTab);

        javax.swing.GroupLayout basicStatsTabLayout = new javax.swing.GroupLayout(basicStatsTab);
        basicStatsTab.setLayout(basicStatsTabLayout);
        basicStatsTabLayout.setHorizontalGroup(
            basicStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicStatisticsPanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        basicStatsTabLayout.setVerticalGroup(
            basicStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicStatsTabLayout.createSequentialGroup()
                .addComponent(basicStatisticsPanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 424, Short.MAX_VALUE))
        );

        geneDetailtabViewSection.addTab("Basic Statistics", basicStatsTab);

        javax.swing.GroupLayout exploreGenesTabLayout = new javax.swing.GroupLayout(exploreGenesTab);
        exploreGenesTab.setLayout(exploreGenesTabLayout);
        exploreGenesTabLayout.setHorizontalGroup(
            exploreGenesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geneExplorerOverview, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        exploreGenesTabLayout.setVerticalGroup(
            exploreGenesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exploreGenesTabLayout.createSequentialGroup()
                .addComponent(geneExplorerOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        geneDetailtabViewSection.addTab("Explore Genes", exploreGenesTab);

        gtfFileUploadButton.setText("upload .gff File");
        gtfFileUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtfFileUploadButtonActionPerformed(evt);
            }
        });

        fastaFileUploadButton.setText("upload fasta file");
        fastaFileUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastaFileUploadButtonActionPerformed(evt);
            }
        });

        fileSelectedLabel.setText("ONLY GTF AND FASTA FILES ARE SUPPORTED");

        javax.swing.GroupLayout fileUploadAreaLayout = new javax.swing.GroupLayout(fileUploadArea);
        fileUploadArea.setLayout(fileUploadAreaLayout);
        fileUploadAreaLayout.setHorizontalGroup(
            fileUploadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileUploadAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fileUploadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileSelectedLabel)
                    .addComponent(fastaFileSelectedLabel)
                    .addGroup(fileUploadAreaLayout.createSequentialGroup()
                        .addComponent(gtfFileUploadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fastaFileUploadButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fileUploadAreaLayout.setVerticalGroup(
            fileUploadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileUploadAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fileUploadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gtfFileUploadButton)
                    .addComponent(fastaFileUploadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileSelectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fastaFileSelectedLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geneDetailtabViewSection)
            .addComponent(fileUploadArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fileUploadPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(fileUploadPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileUploadArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geneDetailtabViewSection)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void gtfFileUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtfFileUploadButtonActionPerformed
        // TODO add your handling code here:
        // File selection dialog
        FileDialog nameBox;
        nameBox = new FileDialog(this, "Open .gff File", FileDialog.LOAD);
        nameBox.setVisible(true);
        String namePath = processSelectedFile(nameBox);

        // Validate file extension
        if (namePath.endsWith(".gff")) {
            fileSelectedLabel.setText("Selected GFF file: " + nameBox.getFile());
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid file type. Please select a valid .gff file.",
                    "File Selection Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        geneExplorerOverview.setExplorerGffFilePath(namePath);

        // Define GFF column headers
        String[] columnHeaders = {
            "Chromosome", "Source", "Feature", "Start", "End", "Score", "Strand", "Phase", "Attributes"
        };

        // Parse GFF data
        Object[][] tableData = parseGffFile(namePath);

 
        // Update the JTable with parsed data
        JTable tablePane = tableViewerOverviewGtfTable.getTablePane();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(tableData, columnHeaders) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table cells non-editable
            }
        };
        tablePane.setModel(model);
        tablePane.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Enable horizontal scrolling

        // Adjust column widths dynamically
        for (int i = 0; i < tablePane.getColumnCount(); i++) {
            TableColumn column = tablePane.getColumnModel().getColumn(i);
            int preferredWidth = 150; // Default width
            for (int row = 0; row < tablePane.getRowCount(); row++) {
                TableCellRenderer renderer = tablePane.getCellRenderer(row, i);
                Component comp = tablePane.prepareRenderer(renderer, row, i);
                preferredWidth = Math.max(comp.getPreferredSize().width, preferredWidth);
            }
            column.setPreferredWidth(preferredWidth);
        }

    }//GEN-LAST:event_gtfFileUploadButtonActionPerformed


    private void fastaFileUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastaFileUploadButtonActionPerformed
        // TODO add your handling code here:
        // Display the file chooser dialog on the EDT
        FileDialog nameBox = new FileDialog(this, "Open .fasta File", FileDialog.LOAD);
        nameBox.setVisible(true); // FileDialog is modal, so this won't block the UI

        // Process the selected file
        String namePath = processSelectedFile(nameBox);
        if (namePath != null && (namePath.endsWith(".fasta") || namePath.endsWith(".fa"))) {
            fastaPath = namePath;
            geneExplorerOverview.setExplorerFastaFilePath(fastaPath);
            // Start background processing
            new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() {
                    // Load the FASTA file in a background thread
                    TextPaneUtil.toggleApplicationLoader(getOwnFrame(), true);
                    sequenceViewerOverview.loadupFastaFile(
                            namePath,
                            basicStatisticsPanelOverview.getTextPane(),
                            geneExplorerOverview
                    );

                    return null;
                }

                @Override
                protected void done() {
                    // Update the UI once processing is complete
                    fastaFileSelectedLabel.setText("Selected Fasta file: " + nameBox.getFile());

                }
            }.execute();
        } else {
            // Handle invalid file selection
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid file type. Please select a valid fasta file.",
                    "File Selection Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_fastaFileUploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GenomeBrowser.BasicStatisticsPanel basicStatisticsPanelOverview;
    private javax.swing.JPanel basicStatsTab;
    private javax.swing.JPanel exploreGenesTab;
    private javax.swing.JLabel fastaFileSelectedLabel;
    private javax.swing.JButton fastaFileUploadButton;
    private javax.swing.JLabel fileSelectedLabel;
    private javax.swing.JPanel fileUploadArea;
    private GenomeBrowser.FileUploadPanel fileUploadPanel5;
    private javax.swing.JTabbedPane geneDetailtabViewSection;
    private GenomeBrowser.GeneExplorer geneExplorerOverview;
    private javax.swing.JButton gtfFileUploadButton;
    private javax.swing.JPanel overviewTab;
    private javax.swing.JPanel rootPanel;
    private GenomeBrowser.SequenceViewer sequenceViewerOverview;
    private GenomeBrowser.TableViewer tableViewerOverviewGtfTable;
    // End of variables declaration//GEN-END:variables
}
